### PR TITLE
Unified Meson DVB driver

### PR DESCRIPTION
**Pull request by afl1**
Mainline compatible dvb driver for Amlogic devices.
I added dtb for following devices:
WeTek Play2
Khadas VIM2 + VTV board
MeCool KI Plus
MeCool KII Pro
MeCool KI Pro
MeCool KI Plus (S905D)
MeCool KII Pro (S905D)
MeCool M8S Pro DVB-T/T2
Magicsee C300 DVB S2 + T2 / C

### CODE REVIEW

**Comment by 150balbes** [comment]
Am I confused, is this PR working or am I not allowed to use it (it was created by mistake) ?

**Comment by afl1** [comment]
It is working, but I had issue to rebuild it. I double check it and I can't find  any bug. Probably I have to try clean build. You can try to build it.

**Comment by 150balbes** [comment]
I'll check it in the next few days and write the result.

**Comment by afl1** [comment]
I push typo fixies in dtb's causing build issue.

**Comment by afl1** [comment]
I fixed typo in dvb-latest and I selected coresponding version to mainline kernel. I removed crazycat from options as I can't find useable  version.

**Comment by 150balbes** [comment]
10 minutes ago I put together a test version with the first version of the patch. Now I need to test it on VIM2. After that I will try the second version of the patch. Question. If everything works, can I send these changes to the main git Libreelec ?

**Comment by afl1** [comment]
There is a issue with vdec.h and vdec.c. Same name is used in Qcom Venus driver. For building dvb-latest or crazycat all files must have unique name. We have to ask @elyotna to rename them e.g. meson_vdec.h.

**Comment by afl1** [comment]
Yes, of course. Driver is open source.

**Comment by superna9999** [comment]
@afl1 Hi, thanks for working on this !

But could you submit this dvb driver upstream ? It would be very valuable (and a good way to sustain your work) to push it for mainline linux, it's not really hard, but needs some help for the first steps.

You can have some help on #linux-amlogic on freenode, or we have a LibreELEC slack server we could invite you on to help you on this process !!

Neil

**Comment by afl1** [comment]
@superna9999 This is work in progress. The driver  is new and need more testing. For now I can upsteam only pimux for ts inputs.

**Comment by 150balbes** [comment]
Test image (add driver alf1)
The images run on any S905 and s912 , but I don't know how to check DVB (I don't have such hardware now).
https://yadi.sk/d/7E-Vsza1tSFUlQ

**Comment by afl1** [comment]
@150balbes Sorry for late answer. You probably released old version. There is no support for dvb. I can't see dtb's for new devices. You have to find in build kernel modules meson-vdec.ko, dvb_meson.ko, wetekdvb.ko and aml_fe.ko.

**Comment by 150balbes** [comment]
> @150balbes Sorry for late answer. You probably released old version. There is no support for dvb. I can't see dtb's for new devices. You have to find in build kernel modules meson-vdec.ko, dvb_meson.ko, wetekdvb.ko and aml_fe.ko.

What version of the image are you trying ? Specify which additional DTB is about. I just launched an image from the site on VIM2 and checked the modules you listed with the "modprobe" command. Everyone's downloading. That means they're in the system.

**Comment by afl1** [comment]
From you link (2019-test-dvb). 
New dtb's : 
`meson-gxbb-ki-plus.dtb`
`meson-gxbb-kii-pro.dtb`
`meson-gxl-s905d-c300-pro.dtb`
`meson-gxl-s905d-ki-plus.dtb`
`meson-gxl-s905d-ki-pro.dtb`
`meson-gxl-s905d-kii-pro.dtb`
`meson-gxl-s905d-m8s-dvb.dtb`

**Comment by 150balbes** [comment]
Yes, I guess I missed some patch files (for Linux). I'll check and add.

**Comment by 150balbes** [comment]
Updated the images on a revised version 20190122_test_dvb

**Comment by afl1** [comment]
I fixed incompatibility between kernel and media_tree causing meson-vdec crash. Now in dvb latest drivers addon is running HW decoding. I tested it with Khadas VIM2.

**Comment by 150balbes** [comment]
Updated the images on a revised version 

20190123_test_dvb

**Comment by 150balbes** [comment]
@afl1 
I suggest we move on to another option. I will create a separate branch "test_dvb" in my GIT, and offer all patches for DVB to place there. This will simplify the debugging process. After everything works properly, I can move it to the main branch.

**Comment by afl1** [comment]
ok

**Comment by 150balbes** [comment]
add branch test-dvb

**Comment by afl1** [comment]
Moved to branch test-dvb.

**Pull request closed without merging**
