### PR TITLE
compile ffmpeg for rockchip-5.0 without --enable-v4l2-request

### PR DESCRIPTION
**Pull request by bartman081523**
if $LINUX=rockchip-5.0, ffmpeg build fails with
Unknown option "--enable-v4l2-request".
See ./configure --help for available options.
FAILURE: scripts/install ffmpeg has failed!

### CODE REVIEW

**Comment by bartman081523** [comment]
sorry, this looks like your working branch. should i pull for master?

**Comment by 150balbes** [comment]
Branch Amlogic-Leia-4.x is basic. It is build to my version for Rockchip.

**Comment by 150balbes** [comment]
I will check this PR and if everything works, I will include in structure.

**Comment by bartman081523** [comment]
error. need help with rockchip-5.0 statement.
but besides that LINUX=rockchip-5.0 build successfully with patched --enable-v4l2-request for ffmpeg.
will test later. but as i said i have problem implementing the rockchip-4.4 or rockchip-5.0 statement in this source.
/Lakka/LibreELEC.tv/packages/multimedia/ffmpeg/package.mk: line 40: rockchip-5.0: command not found

**Pull request closed without merging**
