### PR TITLE
IRQ handling fixes and new dvb devices.

### PR DESCRIPTION
**Pull request by afl1**

### CODE REVIEW

**Comment by afl1** [comment]
I tested this version on MeCool KI Pro and Khadas VIM2 + VTV board. DVB, Ethernet and WiFi are working.

**Comment by 150balbes** [comment]
> I tested this version on MeCool KI Pro and Khadas VIM2 + VTV board. DVB, Ethernet and WiFi are working.

What would I understand, the correctness of my build, can you check my image, how it works with DVB on your models ?

**Comment by afl1** [comment]
Pls, merge PR, irq handling is important fix. Build new versions then I'll test them.

**Comment by 150balbes** [comment]
Ok

**Comment by 150balbes** [comment]
@afl1 I added the latest changes and tried to build a version for the S905 project. But get error from packet (media_tree_aml). Can you check your builds and make corrections ?

**Pull request merged**
